version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: gcr.io/impactful-study-385516/beefy-backend:v10
    container_name: django_container
    command: python manage.py runserver 0.0.0.0:8000
